[이지은] 주문 OrderListView 구현
wecode-bootcamp-korea/26-1st-LIKE-backend pull request #14
Opened 2021-11-09 07:23 UTC by eazisilver

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 주문 및 주문내역 조회

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. orders/views.py
- OrderListView 구현
  - 상품 주문 및 주문한 내역 조회
    > GET /orders
    > POST /orders

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- `select_related`, `prefetch_related` 를 사용해서 정참조 및 역참조로 필요한 데이터 한번에 조회할 수 있도록 queryset 작성
<br />

## :: 기타 질문 및 특이 사항
-

2021-11-09 12:44 UTC, jamessoun93 requested changes

2021-11-09 12:44 UTC, jamessoun93 commented on orders/views.py
> +                    order_status_id   = '2',                # 주문완료
이런값은 Enum class 를 직접 구현해서 넣어줄 수 있도록 해주세요.
그렇게 하면 주석도 불필요하고 항상 의미에 맞는 정확한 값을 넣어줄 수 있습니다.

2021-11-09 23:56 UTC, eazisilver commented on orders/views.py
> +                    order_status_id   = '2',                # 주문완료
아차 그 생각을 못했네요 적용했어요 감사합니다!

2021-11-10 07:15 UTC, jamessoun93 approved these changes
LGTM 👍

2021-11-10 07:15 UTC, merged