모델링 기반으로 App 생성 및 models.py 작성
wecode-bootcamp-korea/26-1st-LIKE-backend pull request #2
Opened 2021-11-02 10:17 UTC by eazisilver

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 모델링 기반으로 models.py 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. users, products. orders app 생성

2. app별 models.py 작성 
- 모델링 기반으로 models.py 작성
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- soft delete 개념을 처음 알았습니다.
- fit, color 테이블을 각각 두지 않고 option테이블을 두고 관리하는 방법을 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항
-

2021-11-02 14:39 UTC, jamessoun93 requested changes
모델 작성하시느라 수고하셨습니다. 리뷰 남겨드렸으니 확인하고 반영해주세요! 💯

몇가지 추가로 피드백 드리자면,
- PR 을 생성하실때는 꼭 현재 PR 상태를 알 수 있도록 라벨을 활용해주세요.
- `created_at`, `updated_at` 같은 반복적인 시간기록 요소를 작성한다면, 매번 선언하기 보다는 아래와 같이 추상화된 class를 만들고 상속 받아서 구현해 주세요.
```python
class TimeStampModel(models.Model):
    created_at  = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        abstract = True
```

2021-11-02 14:39 UTC, jamessoun93 commented on users/models.py
> +    address      = models.CharField(max_length=1000,blank=True)
간격 통일해주세요!
```suggestion
    address      = models.CharField(max_length=1000, blank=True)
```

2021-11-02 14:39 UTC, jamessoun93 commented on products/models.py
> +    main = models.ForeignKey('MainCategory', on_delete=models.CASCADE)
필드명은 최대한 명확하게 지어주세요.
```suggestion
    main_category = models.ForeignKey('MainCategory', on_delete=models.CASCADE)
```

2021-11-02 14:39 UTC, jamessoun93 commented on products/models.py
> +    thumbnail         = models.CharField(max_length=2000,blank=True)
- 필드명이 이렇게만 써있으면 이게 이미지를 저장하려는 필드인지 이미지 URL을 저장하려는건지 구분이 가지 않습니다.
- `thumbnail_image_url` <- 이렇게 상세하게 지어주세요!

2021-11-02 14:39 UTC, jamessoun93 commented on orders/models.py
> +    status           = models.CharField(max_length=10)
`order_status` 는 정규화를 해줘야하겠죠?

2021-11-02 14:39 UTC, jamessoun93 commented on orders/models.py
> +    deleted_at     = models.DateTimeField(null=True)
쇼핑카트 테이블에 `created_at`, `updated_at`, `deleted_at` 같은 정보들이 필요할까요?

2021-11-02 14:39 UTC, jamessoun93 commented on orders/models.py
> +    deleted_at       = models.DateTimeField(null=True)
`Order` 테이블에 Soft Delete 를 해줘야하는 이유가 있을까요?
취소된 주문건을 생각하신거라면 `order_status` 로 관리할 수 있습니다.

2021-11-02 14:39 UTC, jamessoun93 commented on orders/models.py
> +    rating         = models.DecimalField(max_digits=1, decimal_places=1)
max_digits=1, decimal_places=1 으로 의도하신게 맞으신가요??

2021-11-02 14:39 UTC, jamessoun93 commented on orders/models.py
> +    project_option = models.ForeignKey('products.ProductOption', on_delete=models.CASCADE)
project?!?! 오타 수정해주세요.

2021-11-03 03:06 UTC, eazisilver commented on orders/models.py
> +    status           = models.CharField(max_length=10)
`order_status` 상태값 가지고 있는 테이블 생성하라는 말씀이시죠? 😅️

2021-11-03 03:22 UTC, eazisilver commented on orders/models.py
> +    rating         = models.DecimalField(max_digits=1, decimal_places=1)
별점 0.5 ~ 5.0 범위 생각해서 작성했어요!

2021-11-03 04:09 UTC, eazisilver commented on orders/models.py
> +    project_option = models.ForeignKey('products.ProductOption', on_delete=models.CASCADE)
앗, 수정했어요!

2021-11-03 04:09 UTC, eazisilver commented on orders/models.py
> +    deleted_at       = models.DateTimeField(null=True)
넵! 수정했습니다!

2021-11-03 04:10 UTC, eazisilver commented on orders/models.py
> +    deleted_at     = models.DateTimeField(null=True)
필요없겠네요! 수정했습니다!

2021-11-03 04:10 UTC, eazisilver commented on products/models.py
> +    thumbnail         = models.CharField(max_length=2000,blank=True)
변경했어요 :) 감사합니다

2021-11-03 04:12 UTC, eazisilver commented on products/models.py
> +    main = models.ForeignKey('MainCategory', on_delete=models.CASCADE)
넵 디테일한 지적 감사합니다!

2021-11-03 04:13 UTC, eazisilver commented on users/models.py
> +    address      = models.CharField(max_length=1000,blank=True)
넵 .. 수정했습니다!

2021-11-03 04:47 UTC, jamessoun93 commented on orders/models.py
> +    status           = models.CharField(max_length=10)
넵 맞습니다!

2021-11-03 04:47 UTC, jamessoun93 commented on orders/models.py
> +    rating         = models.DecimalField(max_digits=1, decimal_places=1)
그러면 max_digits=2, decimal_places=1 로 해주셔야해요!

2021-11-03 04:50 UTC, jamessoun93 requested changes

2021-11-03 04:50 UTC, jamessoun93 commented on users/models.py
> +    deleted_at   = models.DateTimeField(null=True)
이왕 TimeStampModel 추상 클래스 생성해두신김에 여기도 활용하시면 좋겠네요. 다른 app 에서도 사용하려면 어떤 방법이 있을지 고민해보세요~

2021-11-03 04:55 UTC, eazisilver commented on orders/models.py
> +    rating         = models.DecimalField(max_digits=1, decimal_places=1)
앗 넵 수정했습니다!

2021-11-03 04:59 UTC, eazisilver commented on users/models.py
> +    deleted_at   = models.DateTimeField(null=True)
core app을 생성할까 했는데,, 그럼 다른 app에서도 models를 참조해서 사용할 수 있을 것 같아요!
생각해보니 decorator도 core에 두고 전역처럼 쓰는게 편할 것 같은데..  core app 생성하겠습니다!!

2021-11-03 05:24 UTC, jamessoun93 approved these changes
LGTM 👍
수고하셨습니다!

2021-11-03 05:25 UTC, merged