[이지은] ProductListView 구현
wecode-bootcamp-korea/26-1st-LIKE-backend pull request #7
Opened 2021-11-05 10:32 UTC by eazisilver

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인페이지 상품 리스트 데이터 조회

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. products/urls.py 
- ProductListView 호출 경로 추가 `GET /products`

2. products/views.py
- ProductListView 구현
  - 메인페이지에서 상품 전체 리스트 조회 `GET /products`
  - Main category, size, color에 따른 상품 리스트 필터링 `GET /products?category=신발&color=green&size=255`
    - Q 라이브러리 사용해서 필터링 조건 생성
   
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- Product_Option 테이블의 존재가치를 완전 깨달음.
- color, size 필터링 구현이 Product_Option 테이블 하나로 깔끔하게 처리됨.  
- Q library 사용

<br />

## :: 기타 질문 및 특이 사항
- Postman 스크린 샷
![postman_products](https://user-images.githubusercontent.com/39111959/140475948-10ce59d9-f6f8-4946-90a7-304b2c41e004.png)
&nbsp;
![Screenshot from 2021-11-05 19-28-17](https://user-images.githubusercontent.com/39111959/140497194-28136d01-1084-4af6-9850-6d352b52c9e2.png)

2021-11-06 07:53 UTC, jamessoun93 requested changes
역시 지은님 field lookups 키워드 드리자마자 바로 적용하고 퇴근하시는 모습.. 👍👍👍
결과물도 완벽했지만, 조금의 개선사항이 있어 상세하게 가이드 드렸으니 한번 적용해보세요! 💪

2021-11-06 07:53 UTC, jamessoun93 commented on products/urls.py
> +)
```suggestion
from products.views import ProductListView
```

2021-11-06 07:53 UTC, jamessoun93 commented on products/views.py
> +
구분을 위한 빈 줄은 한줄이면 충분합니다!

2021-11-06 07:53 UTC, jamessoun93 commented on products/views.py
> +            condition.add(Q(size__name=category), Q.AND)
`Q` 객체를 이용한 filter condition 빌드해주는 로직 `field lookups` 까지 활용하여 정말 잘 하셨습니다 👍  

🚧 하지만 혹시 우리가 처리해줘야하는 조건의 수가 많아지면 `if` 문을 그만큼 많이 만들어줘야하는 문제가 있습니다.
조건이 100개라면 `if` 문이 100개가 된다는 뜻이죠.

이런 문제를 해결하기 위해서는 **자료구조**를 활용할 수 있습니다. 약간의 힌트를 드릴테니 한번 고민해보시고 적용해보세요!

1. 처리해줘야하는 `key` 값과 그에 해당하는 `field lookup` 로직을 전부 `hash map (dictionary)` 의 형태로 만들어둔다.
2. `request.GET` 으로 들어오는 `query parameter` 들을 위에서 만들어둔 `dictionary` 필터셋을 활용하여 필터 컨디션들을 담고 있는 `dictionary` 를 만들어준다. **(Hint: dictionary comprehension)**
3. 이렇게 만들어준 필터 컨디션들 담고있는 `dictionary` 를 unpacking 하여 `filter()` 문의 argument 로 넣어줍니다.

한번 순서대로 적용해보시고 어려운 점 있으시면 말씀해주세요 😉💪

2021-11-06 11:42 UTC, eazisilver commented on products/urls.py
> +)
수정했습니다!

2021-11-06 11:42 UTC, eazisilver commented on products/views.py
> +
넵 확인했어요!

2021-11-06 11:49 UTC, eazisilver commented on products/views.py
> +            condition.add(Q(size__name=category), Q.AND)
반영했어요. 감이 잘 안잡혀서 어려웠는데 재밌었어요 😂️
질문있습니다.
1번에서 생성한 `hasp map (dict)`와 2번에서 필터조건을 담고있는 `dictionary`를 get 메서드 안에서 가지고 있는게 맞나요?
ProductListView와 ProductGroupListView에서 중복되게 사용하고 있어서 한곳에서 관리하는 게 더 좋을 것 같아서요.!

2021-11-07 12:14 UTC, jamessoun93 requested changes
"ProductListView 와 ProductGroupListView 합치기" through Slack.

2021-11-07 12:34 UTC, jamessoun93 requested changes

2021-11-07 12:34 UTC, jamessoun93 commented on products/views.py
> +        }
- 여기서 전부 `__in` 을 붙여주신 이유는 dictionary comprehension 에서 `value` 부분이 값이 하나여도 `list` 의 형태로 나와서 이렇게 하신건가요?
- 아니면 실제로 multi-select 가 가능한 경우인가요?

2021-11-07 12:57 UTC, eazisilver commented on products/views.py
> +        }
엇.. `list` 형태로 나와서 `__in` 붙여줬어요..😅️

2021-11-07 13:26 UTC, jamessoun93 commented on products/views.py
> +        }
`value[0]` 이렇게 접근하면 굳이 `IN` 을 사용하지 않아도 되겠죠? 😇

2021-11-07 13:53 UTC, eazisilver commented on products/views.py
> +        }
아! main,sub_category는 단일값이지만 color랑 size는 다중값이라서 저렇게 쓸 수 밖에 없었어요!

2021-11-07 14:57 UTC, jamessoun93 requested changes

2021-11-07 14:57 UTC, jamessoun93 commented on products/views.py
> +            ordering = f"-{ordering.replace('-','')}"
이 부분은 어떤 케이스를 처리해주기 위함인가요?

2021-11-07 14:58 UTC, jamessoun93 requested changes

2021-11-07 14:58 UTC, jamessoun93 commented on products/views.py
> +            "price"               : product.price,
가격은 string 형태로 반환되지 않게 float 로 처리해주세요!

2021-11-07 16:25 UTC, eazisilver commented on products/views.py
> +            ordering = f"-{ordering.replace('-','')}"
ProductOption에서 Product의 price 값을 가져왔었어야 했는데 기준을 Product로 변경해서 저 부분은 필요 없겠네요.
수정할게요!

2021-11-07 16:30 UTC, eazisilver commented on products/views.py
> +            "price"               : product.price,
넵! 수정했습니다 :)

2021-11-08 03:49 UTC, jamessoun93 requested changes

2021-11-08 03:49 UTC, jamessoun93 commented on products/views.py
> +        ordering = '-id' if sort == None else sort
이 부분 기존처럼 sort = request.GET.get('sort', '-id') 해서 default 설정해주시면 되는데 ternary operator 로 변경하신 이유가 있을까요?

2021-11-08 03:55 UTC, eazisilver commented on products/views.py
> +        ordering = '-id' if sort == None else sort
아 그러네요.. ordering 변수를 사용해야한다고 생각해서 그랬던 것 같아요. 수정하겠습니다!

2021-11-08 04:39 UTC, jamessoun93 approved these changes
LGTM 👍

2021-11-08 04:39 UTC, merged