[이지은] 장바구니 CartListView 구현
wecode-bootcamp-korea/26-1st-LIKE-backend pull request #8
Opened 2021-11-08 08:36 UTC by eazisilver

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- login_required decorator 적용하여 로그인된 유저인지 확인
  > decorator가 아직 구현중이므로 적용X
- 장바구니에 담기 & 장바구니 리스트 조회(로그인된 유저인 경우만)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. root urls.py
- CartListView 경로 추가
  > GET /carts or POST /carts

2. orders/views.py
- CartListView 구현
  - 상품 상세페이지의 상품을 장바구니에 담기
    > POST /carts
    > Request  { product_id, size, quantity }
  - 유저 장바구니 리스트
    > GET /carts

  

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 

<br />

## :: 기타 질문 및 특이 사항
-

2021-11-08 14:44 UTC, jamessoun93 requested changes
exception 처리만 해주시면 될 것 같아요~

2021-11-08 14:44 UTC, jamessoun93 commented on orders/views.py
> +            product_option = ProductOption.objects.get(product_id=data['product_id'], size__type=data['size'])
`objects.get()` 에러처리해주세요! (Hint: 2가지 exception 이 발생할 수 있습니다.)

2021-11-08 23:09 UTC, eazisilver commented on orders/views.py
> +            product_option = ProductOption.objects.get(product_id=data['product_id'], size__type=data['size'])
넵 수정했습니다!

2021-11-09 03:07 UTC, jamessoun93 requested changes

2021-11-09 03:07 UTC, jamessoun93 commented on orders/views.py
> +            product_option = ProductOption.objects.get(product_id=data['product_id'], size__type=data['size'])
여러개가 리턴되었을경우에 대한 exception handling 도 추가해주세요.

2021-11-09 03:07 UTC, jamessoun93 commented on orders/views.py
> +            return JsonResponse({"message": "INVALID_SHOPPING_CART"}, status=401)
DoesNotExist exception에 status code 401 은 잘 안어울리네요. 어떤 status code 가 적합할까요?

2021-11-09 07:15 UTC, eazisilver commented on orders/views.py
> +            return JsonResponse({"message": "INVALID_SHOPPING_CART"}, status=401)
ProductOption에서는 `product_id` 와 `size`가 복합키 형태라서 한 개만 리턴될 것 같아요!
DoesNotExist exception의 status code는 400 으로 수정했습니닷..!

2021-11-09 12:36 UTC, jamessoun93 approved these changes
LGTM 😁

2021-11-09 12:36 UTC, merged

2021-11-09 23:15 UTC, eazisilver commented on orders/views.py
> +            product_option = ProductOption.objects.get(product_id=data['product_id'], size__type=data['size'])
아 exception 코멘트에 같이 남겼는데 ProductOption에서는 product_id 와 size가 복합키 형태라서 한 개만 리턴될 것 같아요! 그래도 추가할까요??